# Generated by Django 5.0 on 2023-12-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_priority_status_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
