# Generated by Django 5.0 on 2023-12-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='tag_color_type',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
